language: csharp

env:
  global:
    - CONFIGURATION=Release

matrix:
  include:
  - os: linux
    dist: trusty # Ubuntu 14.04
    dotnet: 1.0.1
    mono: none
    env: DOTNETCORE=1
    sudo: required
  - os: osx
    osx_image: xcode7.3 # macOS 10.11
    dotnet: 1.0.1
    mono: none
    env: DOTNETCORE=1

install:
   - sed -i.bak 's/net451;netstandard/netstandard/g' src/Confluent.Kafka/Confluent.Kafka.csproj
   - dotnet restore

script:
   - make build
   - make test
