name: confluent-kafka-dotnet
lang: unknown
lang_version: unknown
git:
  enable: true
github:
  enable: true
  repo_name: confluentinc/confluent-kafka-dotnet
semaphore:
  enable: true
  pipeline_enable: false
  managed_sections:
    - version
    - name
    - agent
    - global_job_config
sonarqube:
  enable: true
  scanner_config:
    sonar.cs.vscoveragexml.reportsPaths: "**/*coverage.xml"
